openapi: 3.0.0
info:
  title: Update Commentaries API
  version: 1.0.0
paths:
  /commentaries/{projectId}:
    put:
      summary: Update a commentary
      parameters:
        - in: path
          name: projectId
          schema:
            type: integer
          required: true
          description: ID of the project
          content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: A list of commentaries updated successfully
        '500':
          description: Internal server error
