version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  createProject:
    build: ./createproject
    ports:
      - "3007:3007"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/project_management
    depends_on:
      - postgres

  deleteProject:
    build: ./deleteproject
    ports:
      - "3008:3008"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/project_management
    depends_on:
      - postgres

  updateProject:
    build: ./updateproject
    ports:
      - "3009:3009"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/project_management
    depends_on:
      - postgres

  readProject:
    build: ./readproject
    ports:
      - "3010:3010"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/project_management
    depends_on:
      - postgres

volumes:
  postgres-data:
