version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  sendNotification:
    build: .
    ports:
      - "3011:3011"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=local
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
