version: '3.8'

services:
  createcommentary:
    build:
      context: ./createcommentary
    container_name: createcommentary
    ports:
      - "3014:3014"
    env_file:
      - .env 

  readcommentaries:
    build:
      context: ./readcommentaries
    container_name: readcommentaries
    ports:
      - "3015:3015"
    env_file:
      - .env 

  updatecommentary:
    build:
      context: ./updatecommentary
    container_name: updatecommentary
    ports:
      - "3016:3016"
    env_file:
      - .env 
  deletecommentary:
    build:
      context: ./deletecommentary
    container_name: deletecommentary
    ports:
      - "3017:3017"
    env_file:
      - .env 

  createproject:
    build:
      context: ./createproject
    container_name: createproject
    ports:
      - "3018:3018"
    env_file:
      - .env 

  readproject:
    build:
      context: ./readproject
    container_name: readproject
    ports:
      - "3010:3010"
    env_file:
      - .env 
  updateproject:
    build:
      context: ./updateproject
    container_name: updateproject
    ports:
      - "3009:3009"
    env_file:
      - .env 

  deleteproject:
    build:
      context: ./deleteproject
    container_name: deleteproject
    ports:
      - "3008:3008"
    env_file:
      - .env 

  notificationhistory:
    build:
      context: ./notificationhistory
    container_name: notificationhistory
    ports:
      - "3013:3013"
    env_file:
      - .env 

  receivenotification:
    build:
      context: ./receivenotification
    container_name: receivenotification
    ports:
      - "3012:3012"
    env_file:
      - .env 
  sendnotification:
    build:
      context: ./sendnotification
    container_name: sendnotification
    ports:
      - "3011:3011"
    env_file:
      - .env 

  create-user:
    build:
      context: ./create-user
    container_name: create-user
    ports:
      - "3001:3001"
    env_file:
      - .env 

  read-user:
    build:
      context: ../read-user
    container_name: read-user
    ports:
      - "3002:3002"
    env_file:
      - .env 
          
  update-user:
    build:
      context: ../update-user
    container_name: update-user
    ports:
      - "3003:3003"
    env_file:
      - .env 
  delete-user:
    build:
      context: ./delete-user
    container_name: delete-user
    ports:
      - "3004:3004"
    env_file:
      - .env 

  login:
    build:
      context: ./login
    container_name: login
    ports:
      - "3006:3006"
    env_file:
      - .env 

  createdocument:
    build:
      context: ./createdocument
    container_name: createdocument
    ports:
      - "3019:3019"
    env_file:
      - .env 

  deletedocument:
    build:
      context: ./deletecommentary
    container_name: deletecommentary
    ports:
      - "3022:3022"
    env_file:
      - .env 

  readdocument:
    build:
      context: ../readdocument
    container_name: readdocument
    ports:
      - "3020:3020"
    env_file:
      - .env 
    
  updatedocument:
    build:
      context: ./updatedocument
    container_name: updatedocument
    ports:
      - "3021:3021"
    env_file:
      - .env 