version: '3.8'

services:
  createcommentary:
    build:
      context: ../createcommentary
    container_name: createcommentary
    ports:
      - "3014:3014"
    environment:
      - COMMENTARY_DB_HOST=${COMMENTARY_DB_HOST}
      - COMMENTARY_DB_USER=${COMMENTARY_DB_USER}
      - COMMENTARY_DB_PASSWORD=${COMMENTARY_DB_PASSWORD}
      - COMMENTARY_DB_NAME=${COMMENTARY_DB_NAME}
      - COMMENTARY_DB_PORT=${COMMENTARY_DB_PORT}

  readcommentaries:
    build:
      context: ../readcommentaries
    container_name: readcommentaries
    ports:
      - "3015:3015"
    environment:
      - COMMENTARY_DB_HOST=${COMMENTARY_DB_HOST}
      - COMMENTARY_DB_USER=${COMMENTARY_DB_USER}
      - COMMENTARY_DB_PASSWORD=${COMMENTARY_DB_PASSWORD}
      - COMMENTARY_DB_NAME=${COMMENTARY_DB_NAME}
      - COMMENTARY_DB_PORT=${COMMENTARY_DB_PORT}

  updatecommentary:
    build:
      context: ../updatecommentary
    container_name: updatecommentary
    ports:
      - "3016:3016"
    environment:
      - COMMENTARY_DB_HOST=${COMMENTARY_DB_HOST}
      - COMMENTARY_DB_USER=${COMMENTARY_DB_USER}
      - COMMENTARY_DB_PASSWORD=${COMMENTARY_DB_PASSWORD}
      - COMMENTARY_DB_NAME=${COMMENTARY_DB_NAME}
      - COMMENTARY_DB_PORT=${COMMENTARY_DB_PORT}

  deletecommentary:
    build:
      context: ../deletecommentary
    container_name: deletecommentary
    ports:
      - "3017:3017"
    environment:
      - COMMENTARY_DB_HOST=${COMMENTARY_DB_HOST}
      - COMMENTARY_DB_USER=${COMMENTARY_DB_USER}
      - COMMENTARY_DB_PASSWORD=${COMMENTARY_DB_PASSWORD}
      - COMMENTARY_DB_NAME=${COMMENTARY_DB_NAME}
      - COMMENTARY_DB_PORT=${COMMENTARY_DB_PORT}

  createproject:
    build:
      context: ../createproject
    container_name: createproject
    ports:
      - "3018:3018"
    environment:
      - PROJECT_DB_HOST=${PROJECT_DB_HOST}
      - PROJECT_DB_USER=${PROJECT_DB_USER}
      - PROJECT_DB_PASSWORD=${PROJECT_DB_PASSWORD}
      - PROJECT_DB_NAME=${PROJECT_DB_NAME}
      - PROJECT_DB_PORT=${PROJECT_DB_PORT}

  readproject:
    build:
      context: ../readproject
    container_name: readproject
    ports:
      - "3010:3010"
    environment:
      - PROJECT_DB_HOST=${PROJECT_DB_HOST}
      - PROJECT_DB_USER=${PROJECT_DB_USER}
      - PROJECT_DB_PASSWORD=${PROJECT_DB_PASSWORD}
      - PROJECT_DB_NAME=${PROJECT_DB_NAME}
      - PROJECT_DB_PORT=${PROJECT_DB_PORT}

  updateproject:
    build:
      context: ../updateproject
    container_name: updateproject
    ports:
      - "3009:3009"
    environment:
      - PROJECT_DB_HOST=${PROJECT_DB_HOST}
      - PROJECT_DB_USER=${PROJECT_DB_USER}
      - PROJECT_DB_PASSWORD=${PROJECT_DB_PASSWORD}
      - PROJECT_DB_NAME=${PROJECT_DB_NAME}
      - PROJECT_DB_PORT=${PROJECT_DB_PORT}

  deleteproject:
    build:
      context: ../deleteproject
    container_name: deleteproject
    ports:
      - "3008:3008"
    environment:
      - PROJECT_DB_HOST=${PROJECT_DB_HOST}
      - PROJECT_DB_USER=${PROJECT_DB_USER}
      - PROJECT_DB_PASSWORD=${PROJECT_DB_PASSWORD}
      - PROJECT_DB_NAME=${PROJECT_DB_NAME}
      - PROJECT_DB_PORT=${PROJECT_DB_PORT}

  notificationhistory:
    build:
      context: ../notificationhistory
    container_name: notificationhistory
    ports:
      - "3013:3013"
    environment:
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE_NAME=${NOTIFICATION_DB_TABLE_NAME}

  receivenotification:
    build:
      context: ../receivenotification
    container_name: receivenotification
    ports:
      - "3012:3012"
    environment:
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE_NAME=${NOTIFICATION_DB_TABLE_NAME}
  sendnotification:
    build:
      context: ../sendnotification
    container_name: sendnotification
    ports:
      - "3011:3011"
    environment:
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE_NAME=${NOTIFICATION_DB_TABLE_NAME}

  create-user:
    build:
      context: ../create-user
    container_name: create-user
    ports:
      - "3001:3001"
    environment:
      - USER_DB_HOST=${USER_DB_HOST}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_PORT=${USER_DB_PORT}

  read-user:
    build:
      context: ../read-user
    container_name: read-user
    ports:
      - "3002:3002"
    environment:
      - USER_DB_HOST=${USER_DB_HOST}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_PORT=${USER_DB_PORT}
          
  update-user:
    build:
      context: ../update-user
    container_name: update-user
    ports:
      - "3003:3003"
    environment:
      - USER_DB_HOST=${USER_DB_HOST}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_PORT=${USER_DB_PORT}

  delete-user:
    build:
      context: ./delete-user
    container_name: delete-user
    ports:
      - "3004:3004"
    environment:
      - USER_DB_HOST=${USER_DB_HOST}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_PORT=${USER_DB_PORT}

  login:
    build:
      context: ./login
    container_name: login
    ports:
      - "3006:3006"
    environment:
      - USER_DB_HOST=${USER_DB_HOST}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_PORT=${USER_DB_PORT}

  createdocument:
    build:
      context: ./createdocument
    container_name: createdocument
    ports:
      - "3019:3019"
    environment:
      - DOCUMENT_DB_HOST=${DOCUMENT_DB_HOST}
      - DOCUMENT_DB_USER=${DOCUMENT_DB_USER}
      - DOCUMENT_DB_PASSWORD=${DOCUMENT_DB_PASSWORD}
      - DOCUMENT_DB_NAME=${DOCUMENT_DB_NAME}
      - DOCUMENT_DB_PORT=${DOCUMENT_DB_PORT}

  deletedocument:
    build:
      context: ./deletecommentary
    container_name: deletecommentary
    ports:
      - "3022:3022"
    environment:
      - DOCUMENT_DB_HOST=${DOCUMENT_DB_HOST}
      - DOCUMENT_DB_USER=${DOCUMENT_DB_USER}
      - DOCUMENT_DB_PASSWORD=${DOCUMENT_DB_PASSWORD}
      - DOCUMENT_DB_NAME=${DOCUMENT_DB_NAME}
      - DOCUMENT_DB_PORT=${DOCUMENT_DB_PORT}

  readdocument:
    build:
      context: ../readdocument
    container_name: readdocument
    ports:
      - "3020:3020"
    environment:
      - DOCUMENT_DB_HOST=${DOCUMENT_DB_HOST}
      - DOCUMENT_DB_USER=${DOCUMENT_DB_USER}
      - DOCUMENT_DB_PASSWORD=${DOCUMENT_DB_PASSWORD}
      - DOCUMENT_DB_NAME=${DOCUMENT_DB_NAME}
      - DOCUMENT_DB_PORT=${DOCUMENT_DB_PORT}
    
  updatedocument:
    build:
      context: ./updatedocument
    container_name: updatedocument
    ports:
      - "3021:3021"
    environment:
      - DOCUMENT_DB_HOST=${DOCUMENT_DB_HOST}
      - DOCUMENT_DB_USER=${DOCUMENT_DB_USER}
      - DOCUMENT_DB_PASSWORD=${DOCUMENT_DB_PASSWORD}
      - DOCUMENT_DB_NAME=${DOCUMENT_DB_NAME}
      - DOCUMENT_DB_PORT=${DOCUMENT_DB_PORT}