version: '3.8'

services:
  # Traefik service
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"       # Externo -> Interno
      - "443:443"     # Externo -> Interno
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.yourdomain.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"

  # REACT Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    networks:
      - web

  # Microservice: login (Python)
  login:
    build:
      context: ./login
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.login.rule=Host(`login.yourdomain.com`)"
      - "traefik.http.services.login.loadbalancer.server.port=5000"

  # Microservice: create-user
  create-user:
    build:
      context: ./create-user
    ports:
      - "4001:4001"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.create-user.rule=Host(`create-user.yourdomain.com`)"
      - "traefik.http.services.create-user.loadbalancer.server.port=4001"

  # Microservice: delete-user
  delete-user:
    build:
      context: ./delete-user
    ports:
      - "4002:4002"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.delete-user.rule=Host(`delete-user.yourdomain.com`)"
      - "traefik.http.services.delete-user.loadbalancer.server.port=4002"

  # Microservice: update-user
  update-user:
    build:
      context: ./update-user
    ports:
      - "4003:4003"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.update-user.rule=Host(`update-user.yourdomain.com`)"
      - "traefik.http.services.update-user.loadbalancer.server.port=4003"

# Microservice: update-user
  read-user:
    build:
      context: ./read-user
    ports:
      - "4004:4004"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.read-user.rule=Host(`read-user.yourdomain.com`)"
      - "traefik.http.services.read-user.loadbalancer.server.port=4004"

  # Microservice: createproject
  createproject:
    build:
      context: ./createproject
    ports:
      - "4005:4005"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.createproject.rule=Host(`createproject.yourdomain.com`)"
      - "traefik.http.services.createproject.loadbalancer.server.port=4005"

  # Microservice: deleteproject
  deleteproject:
    build:
      context: ./deleteproject
    ports:
      - "4006:4006"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.deleteproject.rule=Host(`deleteproject.yourdomain.com`)"
      - "traefik.http.services.deleteproject.loadbalancer.server.port=4006"

  # Microservice: updateproject
  updateproject:
    build:
      context: ./updateproject
    ports:
      - "4007:4007"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.updateproject.rule=Host(`updateproject.yourdomain.com`)"
      - "traefik.http.services.updateproject.loadbalancer.server.port=4007"

  # Microservice: readproject
  readproject:
    build:
      context: ./readproject
    ports:
      - "4008:4008"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.readproject.rule=Host(`readproject.yourdomain.com`)"
      - "traefik.http.services.readproject.loadbalancer.server.port=4008"

  # Microservice: createcommentary
  createcommentary:
    build:
      context: ./createcommentary
    ports:
      - "4009:4009"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.createcommentary.rule=Host(`createcommentary.yourdomain.com`)"
      - "traefik.http.services.createcommentary.loadbalancer.server.port=4009"

  # Microservice: deletecommentary
  deletecommentary:
    build:
      context: ./deletecommentary
    ports:
      - "4010:4010"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.deletecommentary.rule=Host(`deletecommentary.yourdomain.com`)"
      - "traefik.http.services.deletecommentary.loadbalancer.server.port=4010"

  # Microservice: updatecommentary
  updatecommentary:
    build:
      context: ./updatecommentary
    ports:
      - "4011:4011"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.updatecommentary.rule=Host(`updatecommentary.yourdomain.com`)"
      - "traefik.http.services.updatecommentary.loadbalancer.server.port=4011"

  # Microservice: readcommentaries
  readcommentaries:
    build:
      context: ./readcommentaries
    ports:
      - "4012:4012"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.readcommentaries.rule=Host(`readcommentaries.yourdomain.com`)"
      - "traefik.http.services.readcommentaries.loadbalancer.server.port=4012"

  # Microservice: createdocument
  createdocument:
    build:
      context: ./createdocument
    ports:
      - "4013:4013"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.createdocument.rule=Host(`createdocument.yourdomain.com`)"
      - "traefik.http.services.createdocument.loadbalancer.server.port=4013"

  # Microservice: deletedocument
  deletedocument:
    build:
      context: ./deletedocument
    ports:
      - "4014:4014"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.deletedocument.rule=Host(`deletedocument.yourdomain.com`)"
      - "traefik.http.services.deletedocument.loadbalancer.server.port=4014"

  # Microservice: updatedocument
  updatedocument:
    build:
      context: ./updatedocument
    ports:
      - "4015:4015"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.updatedocument.rule=Host(`updatedocument.yourdomain.com`)"
      - "traefik.http.services.updatedocument.loadbalancer.server.port=4015"

  # Microservice: chat (Go + WebSocket)
  chat-service:
    build:
      context: ./chat-service
    ports:
      - "8080:8080"
    working_dir: /app
    command: go run main.go
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.chat.rule=Host(`chat.yourdomain.com`)"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"

  # Microservice: projectSubscriptionService (Kafka)
  projectsubscriptionservice:
    build:
      context: ./projectsubscriptionservice
    ports:
      - "4021:4021"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.projectsubscriptionservice.rule=Host(`projectsubscriptionservice.yourdomain.com`)"
      - "traefik.http.services.projectsubscriptionservice.loadbalancer.server.port=4021"

  # Microservice: user-role-service (MongoDB Atlas)
  user-role-service:
    build:
      context: ./user-role-service
    ports:
      - "4023:4023"
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.http.routers.user-role-service.rule=Host(`user-role-service.yourdomain.com`)"
      - "traefik.http.services.user-role-service.loadbalancer.server.port=4023"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - web

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_MESSAGE_MAX_BYTES: 200000000 
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
    networks:
      - web

      
  # Microservice: createtask-service (TypeScript)
  createtask-service:
    build:
      context: ./createtask-service
    ports:
      - "4024:4024"
    env_file:
      - .env
    working_dir: /app
    command: npm run start
    networks:
      - web
    labels:
      - "traefik.http.routers.createtask-service.rule=Host(`createtask-service.yourdomain.com`)"
      - "traefik.http.services.createtask-service.loadbalancer.server.port=4024"

  # Microservice: readtask-service (gRPC)
  readtask-service:
    build:
      context: ./readtask-service
    ports:
      - "4025:4025"
    env_file:
      - .env
    working_dir: /app
    command: npm run start
    networks:
      - web
    labels:
      - "traefik.http.routers.readtask-service.rule=Host(`readtask-service.yourdomain.com`)"
      - "traefik.http.services.readtask-service.loadbalancer.server.port=4025"

networks:
  web:
    external: true
