version: '3.8'

services:
  createcommentary:
    build:
      context: ../createcommentary
    container_name: createcommentary
    ports:
      - "3014:3014"
    environment:
      - COMMENTARY_DB_HOST=commentary.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - COMMENTARY_DB_USER=admin
      - COMMENTARY_DB_PASSWORD=adminmysql
      - COMMENTARY_DB_NAME=commentariesdb
      - COMMENTARY_DB_PORT=3306
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  readcommentaries:
    build:
      context: ../readcommentaries
    container_name: readcommentaries
    ports:
      - "3015:3015"
    environment:
      - COMMENTARY_DB_HOST=commentary.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - COMMENTARY_DB_USER=admin
      - COMMENTARY_DB_PASSWORD=adminmysql
      - COMMENTARY_DB_NAME=commentariesdb
      - COMMENTARY_DB_PORT=3306

  updatecommentary:
    build:
      context: ../updatecommentary
    container_name: updatecommentary
    ports:
      - "3016:3016"
    environment:
      - COMMENTARY_DB_HOST=commentary.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - COMMENTARY_DB_USER=admin
      - COMMENTARY_DB_PASSWORD=adminmysql
      - COMMENTARY_DB_NAME=commentariesdb
      - COMMENTARY_DB_PORT=3306

  deletecommentary:
    build:
      context: ../deletecommentary
    container_name: deletecommentary
    ports:
      - "3017:3017"
    environment:
      - COMMENTARY_DB_HOST=commentary.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - COMMENTARY_DB_USER=admin
      - COMMENTARY_DB_PASSWORD=adminmysql
      - COMMENTARY_DB_NAME=commentariesdb
      - COMMENTARY_DB_PORT=3306

  createproject:
    build:
      context: ../createproject
    container_name: createproject
    ports:
      - "3018:3018"
    environment:
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  readproject:
    build:
      context: ../readproject
    container_name: readproject
    ports:
      - "3010:3010"
    environment:
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306

  updateproject:
    build:
      context: ../updateproject
    container_name: updateproject
    ports:
      - "3009:3009"
    environment:
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306

  deleteproject:
    build:
      context: ../deleteproject
    container_name: deleteproject
    ports:
      - "3008:3008"
    environment:
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306

  notificationhistory:
    build:
      context: ../notificationhistory
    container_name: notificationhistory
    ports:
      - "3013:3013"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Notifications

  receivenotification:
    build:
      context: ../receivenotification
    container_name: receivenotification
    ports:
      - "3012:3012"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Notifications

  sendnotification:
    build:
      context: ../sendnotification
    container_name: sendnotification
    ports:
      - "3011:3011"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Notifications

  create-user:
    build:
      context: ../create-user
    container_name: create-user
    ports:
      - "3001:3001"
    environment:
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  read-user:
    build:
      context: ../read-user
    container_name: read-user
    ports:
      - "3002:3002"
    environment:
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  update-user:
    build:
      context: ../update-user
    container_name: update-user
    ports:
      - "3003:3003"
    environment:
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  delete-user:
    build:
      context: ../delete-user
    container_name: delete-user
    ports:
      - "3004:3004"
    environment:
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  login:
    build:
      context: ../login
    container_name: login
    ports:
      - "3006:3006"
    environment:
      - USER_DB_HOST=users.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - USER_DB_USER=admin
      - USER_DB_PASSWORD=adminmysql
      - USER_DB_NAME=usersdb
      - USER_DB_PORT=3306

  createdocument:
    build:
      context: ../createdocument
    container_name: createdocument
    ports:
      - "3019:3019"
    environment:
      - DOCUMENT_DB_HOST=documentsdb.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - DOCUMENT_DB_USER=admin
      - DOCUMENT_DB_PASSWORD=adminmysql
      - DOCUMENT_DB_NAME=documentsdb
      - DOCUMENT_DB_PORT=3306
      - PROJECT_DB_HOST=projects.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - PROJECT_DB_USER=admin
      - PROJECT_DB_PASSWORD=adminmysql
      - PROJECT_DB_NAME=projectsdb
      - PROJECT_DB_PORT=3306

  deletedocument:
    build:
      context: ../deletedocument
    container_name: deletedocument
    ports:
      - "3022:3022"
    environment:
      - DOCUMENT_DB_HOST=documentsdb.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - DOCUMENT_DB_USER=admin
      - DOCUMENT_DB_PASSWORD=adminmysql
      - DOCUMENT_DB_NAME=documentsdb
      - DOCUMENT_DB_PORT=3306

  readdocument:
    build:
      context: ../readdocument
    container_name: readdocument
    ports:
      - "3020:3020"
    environment:
      - DOCUMENT_DB_HOST=documentsdb.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - DOCUMENT_DB_USER=admin
      - DOCUMENT_DB_PASSWORD=adminmysql
      - DOCUMENT_DB_NAME=documentsdb
      - DOCUMENT_DB_PORT=3306

  updatedocument:
    build:
      context: ../updatedocument
    container_name: updatedocument
    ports:
      - "3021:3021"
    environment:
      - DOCUMENT_DB_HOST=documentsdb.cp88o8squjfi.us-east-1.rds.amazonaws.com
      - DOCUMENT_DB_USER=admin
      - DOCUMENT_DB_PASSWORD=adminmysql
      - DOCUMENT_DB_NAME=documentsdb
      - DOCUMENT_DB_PORT=3306
