name: Deploy and build dockers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Dockers
      run: |
        services=(
          "create-user" "delete-user" "update-user" "createproject" "deleteproject" 
          "updateproject" "readproject" "createcommentary" "deletecommentary" 
          "updatecommentary" "readcommentaries" "createdocument" "deletedocument" 
          "updatedocument" "login" "chat-service"
          "user-role-service" "createtask-service" "readtask-service"
        )
        
        for service in "${services[@]}"
        do
          if [ -d "$service" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          else
            echo "Failed to find the path of directory of service $service"
            exit 1
          fi
        done

    - name: Build and Push projectSubscriptionService
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projectsubscriptionservice:latest ./projectSubscriptionService
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/projectsubscriptionservice:latest

    - name: Paths of docker-compose
      run: |
        sed -i 's|build: \./|build: ../|g' ./docker/docker-compose.yml
        echo "Content Updated of docker-compose.yml:"
        cat ./docker/docker-compose.yml

    - name: Create network
      run: |
        docker network create web || true

    - name: Execute Docker Compose
      run: |
        docker-compose -f ./docker/docker-compose.yml up -d

  deploy-DigitalOcean:
    needs: [build-and-push] 
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > key
        chmod 600 key

    - name: Install Docker on Droplet
      run: |
        ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} << 'EOF'
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
        EOF
    - name: Verify Docker installation
      run: |
        ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} "docker --version"

    - name: Create network on DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} "docker network create web || true"


    - name: Pull Docker images
      run: |
        services=(
          "create-user" "delete-user" "update-user" "createproject" "deleteproject" 
          "updateproject" "readproject" "createcommentary" "deletecommentary" 
          "updatecommentary" "readcommentaries" "createdocument" "deletedocument" 
          "updatedocument" "login" "chat-service" "projectsubscriptionservice"
          "user-role-service" "createtask-service" "readtask-service"
        )

        for service in "${services[@]}"
        do
          ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest"
        done

    - name: Stop running containers
      run: |
        services=(
          "frontend" "create-user" "delete-user" "update-user" "createproject" "deleteproject" 
          "updateproject" "readproject" "createcommentary" "deletecommentary" 
          "updatecommentary" "readcommentaries" "createdocument" "deletedocument" 
          "updatedocument" "login" "chat-service" "projectsubscriptionservice"
          "user-role-service" "createtask-service" "readtask-service"
        )

        for service in "${services[@]}"
        do
          ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} "sudo docker stop $service-plataform-aws || true"
          ssh -o StrictHostKeyChecking-no -i key root@${{ secrets.DROPLET_IP }} "sudo docker rm $service-plataform-aws || true"
        done

    - name: Remove old Docker images
      run: |
        ssh -o StrictHostKeyChecking-no -i key root@${{ secrets.DROPLET_IP }} 'sudo docker image prune -f'

    - name: Run new containers
      run: |
        services=(
          "frontend" "create-user" "delete-user" "update-user" "read-user" "createproject" "deleteproject" 
          "updateproject" "readproject" "createcommentary" "deletecommentary" 
          "updatecommentary" "readcommentaries" "createdocument" "deletedocument" 
          "updatedocument" "login" "chat-service" "projectsubscriptionservice"
          "user-role-service" "createtask-service" "readtask-service"
        )
        
        ports=(3000 4001 4002 4003 4004 4005 4006 4007 4008 4009 4010 4011 4012 4013 4014 4015 5000 8080 4021 4023 4024 4025)

        for index in ${!services[@]}
        do
          service=${services[$index]}
          port=${ports[$index]}
          ssh -o StrictHostKeyChecking=no -i key root@${{ secrets.DROPLET_IP }} "sudo docker run -d --name $service-plataform-aws -p $port:$port ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest"
        done