name: Deploy and build dockers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Dockers
      run: |
        services=(
          "create-user" "delete-user" "update-user" "createproject" "deleteproject" 
          "updateproject" "readproject" "createcommentary" "deletecommentary" 
          "updatecommentary" "readcommentaries" "createdocument" "deletedocument" 
          "updatedocument" "login" "chat-service" "projectSubscriptionService"
          "user-role-service" "createtask-service" "readtask-service"
        )
        
        for service in "${services[@]}"
        do
          if [ -d "$service" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          else
            echo "Failed to find the path of directory of service $service"
            exit 1
          fi
        done
